services:
  - type: web
    name: startup-connect-hub-backend
    env: python
    region: singapore
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: |
      cd backend
      gunicorn startup_platform.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: startup_platform.settings
      - key: PYTHON_VERSION
        value: 3.12.0
